;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2011-6-21 16:53:29

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1002	1002	; css() css\css.html
#define IDH_1003	1003	; height() 尺寸\height.html
#define IDH_1004	1004	; width() 尺寸\width.html
#define IDH_1000	1000	; Query() 核心\Query()核心函数.html
#define IDH_1001	1001	; Query.noConflict() 核心\Query.noConflict.html
#define IDH_1038	1038	; children() 筛选\children().html
#define IDH_1039	1039	; eq() 筛选\eq().html
#define IDH_1042	1042	; hasClass() 筛选\hasClass.html
#define IDH_1041	1041	; not() 筛选\not().html
#define IDH_1037	1037	; parent() 筛选\parent().html
#define IDH_1040	1040	; siblings() 筛选\siblings().html
#define IDH_1025	1025	; bind() 事件\bind.html
#define IDH_1006	1006	; blur() 事件\blur.html
#define IDH_1018	1018	; change() 事件\change.html
#define IDH_1005	1005	; click() 事件\click.html
#define IDH_1012	1012	; dblclick() 事件\dblclick.html
#define IDH_1024	1024	; error() 事件\error.html
#define IDH_1007	1007	; focus() 事件\focus.html
#define IDH_1021	1021	; keydown() 事件\keydown.html
#define IDH_1022	1022	; keypress() 事件\keypress.html
#define IDH_1023	1023	; keyup() 事件\keyup.html
#define IDH_1008	1008	; load() 事件\load.html
#define IDH_1013	1013	; mousedown() 事件\mousedown.html
#define IDH_1015	1015	; mousemove() 事件\mousemove.html
#define IDH_1017	1017	; mouseout() 事件\mouseout.html
#define IDH_1016	1016	; mouseover() 事件\mouseover.html
#define IDH_1014	1014	; mouseup() 事件\mouseup.html
#define IDH_1009	1009	; resize() 事件\resize.html
#define IDH_1010	1010	; scroll() 事件\scroll.html
#define IDH_1019	1019	; select() 事件\select.html
#define IDH_1020	1020	; submit() 事件\submit.html
#define IDH_1011	1011	; unload() 事件\unload.html
#define IDH_1026	1026	; position() 位置\position.html
#define IDH_1028	1028	; scrollLeft() 位置\scrollLeft.html
#define IDH_1027	1027	; scrollTop() 位置\scrollTop.html
#define IDH_1033	1033	; addClass() 文档操作\addClass.html
#define IDH_1036	1036	; attr() 文档操作\attr.html
#define IDH_1035	1035	; html() 文档操作\html.html
#define IDH_1034	1034	; removeClass() 文档操作\removeClass.html
#define IDH_1031	1031	; className 选择器\className.html
#define IDH_1030	1030	; id 选择器\id.html
#define IDH_1032	1032	; level 选择器\level.html
#define IDH_1029	1029	; tagName 选择器\tagName.html
