;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2011-6-21 16:53:29

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1002=css\css.html	; css()
IDH_1003=尺寸\height.html	; height()
IDH_1004=尺寸\width.html	; width()
IDH_1000=核心\Query()核心函数.html	; Query()
IDH_1001=核心\Query.noConflict.html	; Query.noConflict()
IDH_1038=筛选\children().html	; children()
IDH_1039=筛选\eq().html	; eq()
IDH_1042=筛选\hasClass.html	; hasClass()
IDH_1041=筛选\not().html	; not()
IDH_1037=筛选\parent().html	; parent()
IDH_1040=筛选\siblings().html	; siblings()
IDH_1025=事件\bind.html	; bind()
IDH_1006=事件\blur.html	; blur()
IDH_1018=事件\change.html	; change()
IDH_1005=事件\click.html	; click()
IDH_1012=事件\dblclick.html	; dblclick()
IDH_1024=事件\error.html	; error()
IDH_1007=事件\focus.html	; focus()
IDH_1021=事件\keydown.html	; keydown()
IDH_1022=事件\keypress.html	; keypress()
IDH_1023=事件\keyup.html	; keyup()
IDH_1008=事件\load.html	; load()
IDH_1013=事件\mousedown.html	; mousedown()
IDH_1015=事件\mousemove.html	; mousemove()
IDH_1017=事件\mouseout.html	; mouseout()
IDH_1016=事件\mouseover.html	; mouseover()
IDH_1014=事件\mouseup.html	; mouseup()
IDH_1009=事件\resize.html	; resize()
IDH_1010=事件\scroll.html	; scroll()
IDH_1019=事件\select.html	; select()
IDH_1020=事件\submit.html	; submit()
IDH_1011=事件\unload.html	; unload()
IDH_1026=位置\position.html	; position()
IDH_1028=位置\scrollLeft.html	; scrollLeft()
IDH_1027=位置\scrollTop.html	; scrollTop()
IDH_1033=文档操作\addClass.html	; addClass()
IDH_1036=文档操作\attr.html	; attr()
IDH_1035=文档操作\html.html	; html()
IDH_1034=文档操作\removeClass.html	; removeClass()
IDH_1031=选择器\className.html	; className
IDH_1030=选择器\id.html	; id
IDH_1032=选择器\level.html	; level
IDH_1029=选择器\tagName.html	; tagName
